name: Joke Of The Day
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  joke-of-the-day:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install curl jq perl -y
      - name: update README
        run: bash .github/joke-of-the-day.sh
      - name: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "New joke of the day"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
